<?php

/**
 * @file
 * Style Guides - Component.
 */
?>
<!-----------------------  header-block--search ----------------------->

<div id="sg-header-block--search" class="styleguide">

<h2 class="styleguide-title">header-block--search</h2>

<div class="sg-content">

<div class="styleguide-item-preview">
...
</div>

<div class="styleguide-item-text uitabs">
<ul>
    <li><a href="#tabs-header-block--search-1">CSS</a></li>
    <li><a href="#tabs-header-block--search-2">SCSS</a></li>
    <li><a href="#tabs-header-block--search-3">HTML</a></li>
</ul>

<pre id="tabs-header-block--search-1">
<code class="language-css">
<?php include 'header-block--search.css'; ?>
</code>
</pre>

<pre id="tabs-header-block--search-2">
<code class="language-scss">
<?php include '../sass/components/03-organisms/header/_header-block--search.scss'; ?>
</code>
</pre>

<pre id="tabs-header-block--search-3">
<code class="language-markup">
...
</code>
</pre>

</div>
</div>
</div>
