<?php

/**
 * @file
 * Style Guides - blockquote.
 */
?>
<!-----------------------  blockquote ----------------------->

<div id="sg-blockquote" class="styleguide">

<h2 class="styleguide-title">blockquote</h2>

<div class="sg-content">

<div class="styleguide-item-preview">
<blockquote>
<p>Sed amet dolor justo et dolor voluptua, consetetur amet erat 
sea justo diam takimata clita. Invidunt sanctus nonumy sed ut et 
sed dolores, sea et et et et ipsum voluptua sed clita. Ea labore 
justo ut sed. Invidunt voluptua takimata accusam clita duo, magna 
ipsum amet sanctus accusam kasd magna amet takimata invidunt, eirmod 
diam ipsum magna clita. Dolores dolores.</p>
</blockquote>
</div>

<div class="styleguide-item-text uitabs">
<ul>
    <li><a href="#tabs-blockquote-1">CSS</a></li>
    <li><a href="#tabs-blockquote-2">SCSS</a></li>
    <li><a href="#tabs-blockquote-3">HTML</a></li>
</ul>

<pre id="tabs-blockquote-1">
<code class="language-css">
<?php include 'blockquote.css'; ?>
</code>
</pre>

<pre id="tabs-blockquote-2">
<code class="language-scss">
<?php include '../sass/components/01-atoms/_blockquote.scss'; ?>
</code>
</pre>

<pre id="tabs-blockquote-3">
<code class="language-markup">
&lt;blockquote>
&lt;p>Sed amet dolor justo et dolor voluptua, consetetur amet erat 
sea justo diam takimata clita. Invidunt sanctus nonumy sed ut et 
sed dolores, sea et et et et ipsum voluptua sed clita. Ea labore 
justo ut sed. Invidunt voluptua takimata accusam clita duo, magna 
ipsum amet sanctus accusam kasd magna amet takimata invidunt, eirmod 
diam ipsum magna clita. Dolores dolores.&lt;/p>
&lt;/blockquote>
</code>
</pre>

</div>
</div>
</div>
