<?php

/**
 * @file
 * Style Guides - paragraph.
 */
?>
<!-----------------------  paragraph ----------------------->

<div id="sg-paragraph" class="styleguide">

<h2 class="styleguide-title">paragraph</h2>

<div class="sg-content">

<div class="styleguide-item-preview">
<p>Dolor kasd lorem ipsum et sit sanctus eirmod clita <a href="/">link</a> accusam nonumy. Ea sadipscing duo kasd eos. Stet et ipsum erat.</p>
<p>Dolor kasd lorem ipsum et sit sanctus eirmod clita accusam nonumy. Ea sadipscing duo kasd eos. Stet et ipsum erat. Dolor kasd lorem ipsum et sit sanctus eirmod clita accusam nonumy. Ea sadipscing duo kasd eos. Stet et ipsum erat.</p>
<p>Dolor kasd lorem ipsum et sit sanctus eirmod clita <a href="/">link</a> accusam nonumy. Ea sadipscing duo kasd eos. Stet et ipsum erat.</p>
</div>

<div class="styleguide-item-text uitabs">
<ul>
    <li><a href="#tabs-paragraph-1">CSS</a></li>
    <li><a href="#tabs-paragraph-2">SCSS</a></li>
    <li><a href="#tabs-paragraph-3">HTML</a></li>
</ul>

<pre id="tabs-paragraph-1">
<code class="language-css">
<?php include 'paragraph.css'; ?>
</code>
</pre>

<pre id="tabs-paragraph-2">
<code class="language-scss">
<?php include '../sass/components/01-atoms/_paragraph.scss'; ?>
</code>
</pre>

<pre id="tabs-paragraph-3">
<code class="language-markup">
&lt;p>Dolor kasd lorem ipsum et sit sanctus eirmod clita &lt;a href="/">link&lt;/a> accusam nonumy. 
Ea sadipscing duo kasd eos. Stet et ipsum erat.&lt;/p>
&lt;p>Dolor kasd lorem ipsum et sit sanctus eirmod clita accusam nonumy. Ea sadipscing duo kasd eos. 
Stet et ipsum erat. Dolor kasd lorem ipsum et sit sanctus eirmod clita accusam nonumy. 
Ea sadipscing duo kasd eos. Stet et ipsum erat.&lt;/p>
&lt;p>Dolor kasd lorem ipsum et sit sanctus eirmod clita &lt;a href="/">link&lt;/a> accusam nonumy. 
Ea sadipscing duo kasd eos. Stet et ipsum erat.&lt;/p>
</code>
</pre>

</div>
</div>
</div>
